-- Curated oral-care products from the docs fluoride workbook.
-- Verdicts, confidence, matches, and guidance are recomputed with fluorideEngine/config v1.3.
-- Safe to rerun: existing oral_care rows with the same normalized product name are skipped.
-- No barcode is supplied in the source workbook; barcode remains NULL.
-- 54 classifiable products included; 1 unclassified products withheld for review.

begin;

do $guard$
begin
  if not exists (
    select 1 from public.lookup_config
    where category = 'oral_care' and version = '1.3' and is_published = true
  ) then
    raise exception 'Publish oral_care lookup_config version 1.3 before importing products.';
  end if;
end;
$guard$;

with incoming (name, brand, subcategory, ingredients_text, result_tier, result_label, confidence_tier, matched_terms, guidance_text, config_version) as (
  values
  ('Crest 3D White Radiant Mint', 'Crest', 'toothpaste_gel', 'sodium fluoride 0.243%, water, sorbitol, hydrated silica, disodium pyrophosphate, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Colgate Total Clean Mint', 'Colgate', 'toothpaste_gel', 'stannous fluoride 0.454%, water, sorbitol, hydrated silica, glycerin, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"1099 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Sensodyne Pronamel Daily Protection', 'Sensodyne', 'toothpaste_gel', 'sodium fluoride 0.15% w/v fluoride ion, potassium nitrate, water, sorbitol, hydrated silica', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1500 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Tom''s of Maine Simply White Fluoride-Free', 'Tom''s of Maine', 'toothpaste_gel', 'calcium carbonate, glycerin, water, xylitol, hydrated silica, natural flavor', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Hello Simply White Whitening Toothpaste', 'Hello', 'toothpaste_gel', 'sodium monofluorophosphate 0.76%, hydrated silica, sorbitol, glycerin, water, xylitol', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"1000 ppm"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Boka Ela Mint Toothpaste', 'Boka', 'toothpaste_gel', 'nano-hydroxyapatite, water, vegetable glycerin, hydrated silica, xylitol, mentha piperita oil', 'none', 'Fluoride-Free', 'high', '[{"term":"nano-hydroxyapatite","normalized":"Nano-hydroxyapatite","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Arm & Hammer Advance White Extreme Whitening', 'Arm & Hammer', 'toothpaste_gel', 'sodium fluoride 0.24%, sodium bicarbonate, PEG-8, hydrated silica, glycerin', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1080 ppm"},{"term":"sodium bicarbonate","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Parodontax Clean Mint Gum Toothpaste', 'Parodontax', 'toothpaste_gel', 'stannous fluoride 0.454%, glycerin, PEG-8, hydrated silica, pentasodium triphosphate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"1099 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Marvis Classic Strong Mint', 'Marvis', 'toothpaste_gel', 'aluminum hydroxide, aqua, sorbitol, glycerin, silica, aroma, cellulose gum, sodium monofluorophosphate', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Jason Simply Nude Fluoride-Free Toothpaste', 'Jason', 'toothpaste_gel', 'calcium carbonate, aqua, glycerin, sodium cocoyl glutamate, mentha piperita oil', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Red Seal Natural Herbal Toothpaste', 'Red Seal', 'toothpaste_gel', 'calcium carbonate, purified water, sorbitol, glycerin, sodium lauryl sulphate, mentha piperita oil', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Close-Up Cinnamon Red Gel Toothpaste', 'Close-Up', 'toothpaste_gel', 'sodium monofluorophosphate 0.8%, sorbitol, water, hydrated silica, PEG-32, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"1052 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Pepsodent Cavity Protection Toothpaste', 'Pepsodent', 'toothpaste_gel', 'sodium monofluorophosphate 0.76%, sorbitol, water, hydrated silica, PEG-32, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"1000 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Aim Cavity Protection Ultra Mint Gel', 'Aim', 'toothpaste_gel', 'sodium fluoride 0.24%, sorbitol, water, hydrated silica, PEG-8, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1080 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Oral-B Pro-Expert All-in-One', 'Oral-B', 'toothpaste_gel', 'stannous fluoride, sodium fluoride, water, sorbitol, hydrated silica, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"},{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Signal Family Care Herbal Toothpaste', 'Signal', 'toothpaste_gel', 'sodium monofluorophosphate 1.1%, aqua, calcium carbonate, sorbitol, hydrated silica', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"1447 ppm"},{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Blend-a-med Complete Protect 7', 'Blend-a-med', 'toothpaste_gel', 'sodium fluoride, stannous fluoride, aqua, sorbitol, hydrated silica, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"},{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Elmex Anti-Caries Toothpaste', 'Elmex', 'toothpaste_gel', 'amine fluoride (olaflur) 1400 ppm F, aqua, hydrated silica, sorbitol, hydroxyethylcellulose', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"amine fluoride","normalized":"Amine Fluoride","kind":"active_compound","detail":"1400 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Aronal Strengthening Toothpaste', 'Aronal', 'toothpaste_gel', 'sodium fluoride 1450 ppm F, aqua, sorbitol, hydrated silica, PEG-32, aroma', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1450 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Meridol Gum Protection Toothpaste', 'Meridol', 'toothpaste_gel', 'amine fluoride (olaflur), stannous fluoride, aqua, sorbitol, hydrated silica, hydroxyethylcellulose', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"default ppm for this compound"},{"term":"amine fluoride","normalized":"Amine Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Dontodent Complete 5', 'Dontodent', 'toothpaste_gel', 'sodium fluoride 0.15% w/v fluoride ion, aqua, sorbitol, hydrated silica, sodium C14-16 olefin sulfonate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1500 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Dentalux Junior 6+', 'Dentalux', 'toothpaste_gel', 'sodium fluoride 1450 ppm F, aqua, hydrated silica, sorbitol, propylene glycol, cellulose gum', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1450 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Vitis Anticaries Toothpaste', 'Vitis', 'toothpaste_gel', 'sodium monofluorophosphate, xylitol, aqua, sorbitol, silica, glycerin, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('KORRES Anise & Eucalyptus Fluoride-Free', 'KORRES', 'toothpaste_gel', 'calcium carbonate, aqua, sorbitol, glycerin, hydrated silica, cellulose gum, illicium verum fruit oil', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Dr. Hauschka Med Fortifying Mint Toothpaste', 'Dr. Hauschka', 'toothpaste_gel', 'water, calcium carbonate, glycerin, silica, aesculus hippocastanum seed extract, mentha piperita oil', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Weleda Salt Toothpaste', 'Weleda', 'toothpaste_gel', 'sodium bicarbonate, water, glycerin, silica, mentha piperita oil, prunus spinosa fruit juice', 'none', 'Fluoride-Free', 'high', '[{"term":"sodium bicarbonate","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Lavera Complete Care Fluoride-Free', 'Lavera', 'toothpaste_gel', 'aqua, sorbitol, hydrated silica, calcium carbonate, xylitol, glycerin, aloe barbadensis leaf juice', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Desert Essence Tea Tree Oil Toothpaste', 'Desert Essence', 'toothpaste_gel', 'calcium carbonate, glycerin, water, melaleuca alternifolia leaf oil, sodium cocoyl glutamate', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Kingfisher Baking Soda Fluoride-Free', 'Kingfisher', 'toothpaste_gel', 'calcium carbonate, glycerin, aqua, sodium bicarbonate, sodium lauryl sulfate, hydrated silica', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"sodium bicarbonate","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Colgate Max Fresh Nightfall Mint', 'Colgate', 'toothpaste_gel', 'sodium fluoride 0.243%, sorbitol, water, hydrated silica, PEG-12, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Colgate Kids 2-in-1 Watermelon', 'Colgate', 'toothpaste_gel', 'sodium fluoride 0.24%, sorbitol, water, hydrated silica, PEG-12, tetrasodium pyrophosphate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1080 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Crest Kid''s Strawberry Rush', 'Crest', 'toothpaste_gel', 'sodium fluoride 0.243%, sorbitol, water, hydrated silica, PEG-6, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('TheraBreath Fresh Breath Toothpaste', 'TheraBreath', 'toothpaste_gel', 'sodium fluoride 0.24%, water, sorbitol, hydrated silica, glycerin, xylitol, OXYD-8', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1080 ppm"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Risewell Mineral Toothpaste', 'Risewell', 'toothpaste_gel', 'hydroxyapatite, water, glycerin, hydrated silica, xylitol, mentha piperita oil, stevia rebaudiana', 'none', 'Fluoride-Free', 'high', '[{"term":"hydroxyapatite","normalized":"Nano-hydroxyapatite","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Bite Toothpaste Bits Mint', 'Bite', 'toothpaste_gel', 'nano-hydroxyapatite, erythritol, xylitol, mentha piperita oil, sodium cocoyl glutamate, calcium carbonate', 'none', 'Fluoride-Free', 'high', '[{"term":"nano-hydroxyapatite","normalized":"Nano-hydroxyapatite","kind":"active_compound","detail":"default ppm for this compound"},{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Native Whitening Toothpaste Flouride-Free', 'Native', 'toothpaste_gel', 'calcium carbonate, water, glycerin, hydrated silica, xylitol, sodium cocoyl glutamate, peppermint oil', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Burt''s Bees Purely White Fluoride Toothpaste', 'Burt''s Bees', 'toothpaste_gel', 'sodium fluoride 0.243%, water, hydrated silica, sorbitol, glycerin, xylitol, stevia rebaudiana', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Moon Stain Removal Fluoride Toothpaste', 'Moon', 'toothpaste_gel', 'sodium fluoride 0.243%, water, hydrated silica, sorbitol, glycerin, xylitol, mica, titanium dioxide', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Davids Natural Toothpaste Peppermint', 'Davids', 'toothpaste_gel', 'calcium carbonate, purified water, sodium cocoyl glutamate, mentha piperita oil, stevia rebaudiana', 'none', 'Fluoride-Free', 'high', '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Ciptadent Maxi Fresh', 'Ciptadent', 'toothpaste_gel', 'sodium monofluorophosphate, sodium fluoride, water, sorbitol, hydrated silica, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"},{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Pepsodent Action 123', 'Pepsodent', 'toothpaste_gel', 'sodium monofluorophosphate, calcium carbonate, water, sorbitol, hydrated silica, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Darlie Double Action Mint', 'Darlie', 'toothpaste_gel', 'sodium fluoride 0.221% w/w (1000 ppm F), dicalcium phosphate dihydrate, water, sorbitol, glycerin', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1000 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Zact Lion Smoker''s Toothpaste', 'Lion', 'toothpaste_gel', 'sodium monofluorophosphate, dicalcium phosphate dihydrate, water, sorbitol, PEG-8, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Sangi Apagard Premio', 'Sangi', 'toothpaste_gel', 'medical hydroxyapatite, water, cetylpyridinium chloride, concentrated glycerin, silicic anhydride', 'none', 'Fluoride-Free', 'high', '[{"term":"hydroxyapatite","normalized":"Nano-hydroxyapatite","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3'),
  ('Lion Clinica Advantage Toothpaste', 'Lion', 'toothpaste_gel', 'sodium fluoride 1450 ppm F, sorbitol, PG, PEG-4000, dextranase, baking soda, hydrated silica', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1450 ppm"},{"term":"baking soda","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Sunstar Ora2 Me Stain Clear', 'Sunstar', 'toothpaste_gel', 'sodium fluoride, isopropylmethylphenol, sorbitol, concentrated glycerin, silicic anhydride', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('GUM Dental Paste Toothpaste', 'Sunstar', 'toothpaste_gel', 'sodium fluoride, cetylpyridinium chloride, sorbitol, concentrated glycerin, silica, alkylglycoside', 'medium', 'Standard Fluoride Content', 'medium', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Sensodyne Repair & Protect', 'Sensodyne', 'toothpaste_gel', 'stannous fluoride 0.454%, glycerin, PEG-8, hydrated silica, pentasodium triphosphate, aroma', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"1099 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('Sensodyne Rapid Relief', 'Sensodyne', 'toothpaste_gel', 'stannous fluoride 0.454%, glycerin, PEG-8, hydrated silica, pentasodium triphosphate, sodium lauryl sulfate', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"1099 ppm"}]'::jsonb, 'Typical daily adult cavity protection level.', '1.3'),
  ('ACT Restoring Anticavity Fluoride Mouthwash', 'ACT', 'mouthwash_rinse', 'sodium fluoride 0.05% (0.02% w/v fluoride ion), water, alcohol (11%), sorbitol, poloxamer 407, propylene glycol, sodium benzoate, flavor', 'high', 'High Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"500 ppm"}]'::jsonb, 'High Fluoride Content', '1.3'),
  ('Colgate Phos-Flur Anticavity Rinse', 'Colgate', 'mouthwash_rinse', 'sodium fluoride 0.05% w/v, water, sorbitol, alcohol (6% v/v), phosphate, flavor', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"225 ppm"}]'::jsonb, 'Typical daily anticavity rinse strength.', '1.3'),
  ('Listerine Total Care Anticavity Mouthwash', 'Listerine', 'mouthwash_rinse', 'sodium fluoride 0.02% (0.01% w/v fluoride ion), water, sorbitol solution, alcohol (21.6%), eucalyptol, menthol, methyl salicylate, thymol', 'medium', 'Standard Fluoride Content', 'high', '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"200 ppm"}]'::jsonb, 'Typical daily anticavity rinse strength.', '1.3'),
  ('Listerine Zero Alcohol Antiseptic Mouthwash', 'Listerine', 'mouthwash_rinse', 'water, sorbitol, propylene glycol, poloxamer 407, lauramidopropyl betaine, eucalyptol, benzoic acid, sodium saccharin', 'none', 'Fluoride-Free', 'high', '[]'::jsonb, 'Fluoride-Free', '1.3'),
  ('TheraBreath Fresh Breath Oral Rinse (Green)', 'TheraBreath', 'mouthwash_rinse', 'water, PEG-40 hydrogenated castor oil, sodium chlorite, tetrasodium EDTA, sodium benzoate, sodium bicarbonate, mentha piperita oil', 'none', 'Fluoride-Free', 'high', '[{"term":"sodium bicarbonate","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb, 'Fluoride-Free', '1.3')
), inserted as (
  insert into public.products (
    barcode, name, brand, category, subcategory, ingredients_text,
    result_tier, result_label, confidence_tier, matched_terms,
    guidance_text, config_version
  )
  select
    null, incoming.name, incoming.brand, 'oral_care', incoming.subcategory,
    incoming.ingredients_text, incoming.result_tier::verdict_tier,
    incoming.result_label, incoming.confidence_tier::verdict_tier,
    incoming.matched_terms, incoming.guidance_text, incoming.config_version
  from incoming
  where not exists (
    select 1 from public.products existing
    where existing.category = 'oral_care'
      and lower(btrim(existing.name)) = lower(btrim(incoming.name))
  )
  returning id
)
select count(*) as inserted_this_run from inserted;

select category, count(*) as oral_care_product_count
from public.products
where category = 'oral_care'
group by category;

commit;
