-- Publish the GMO lookup config v1.1.
--
-- Generated by scripts/build-publish-gmo-v1.1.mjs - do not hand-edit. Re-run
-- that script after any change to data/gmo_lookup_config_v1.0.json.
--
-- WHY THIS MUST BE ONE TRANSACTION
--   create unique index one_published_per_category
--     on lookup_config (category) where is_published;
-- permits exactly ONE published ruleset per category. Unpublishing v1.0 and
-- publishing v1.1 are therefore two statements that must not be
-- separable: between them the table would hold no published config, and every
-- scan landing in that window fails closed with
-- "No valid published ruleset is available". PostgREST cannot do that; a single
-- SQL script can.
--
-- HOW TO RUN
--   1. Supabase Dashboard -> your project -> SQL Editor -> New query
--   2. Paste this whole file -> Run
--   3. Read the verification SELECT at the bottom. Expect exactly one row with
--      version = '1.1', is_published = true, version_agrees = true,
--      crop_families = 10.
--
-- SAFE TO RE-RUN: the insert is an upsert on (category, version).
--
-- NOTE: clients cache the published config in IndexedDB for 5 minutes
-- (CACHE_MAX_AGE in src/lib/config/lookupConfig.ts), so a device that scanned
-- moments before this ran keeps using v1.0 until that window elapses.
--
-- ROLLBACK: flip the is_published flags back to v1.0 in the same transaction
-- shape - unpublish v1.1, publish v1.0.

begin;

-- 1. Land the new ruleset UNPUBLISHED first, so it is fully present
--    in the table before anything starts serving from it.
insert into public.lookup_config (category, version, config_json, is_published, published_at)
values (
  'gmo_food',
  '1.1',
  $shfconfig$
{
  "project": "SHF GMO Likelihood Detection — Lookup Config v1.1",
  "version": "1.1",
  "certification_short_circuit": {
    "note": "Check BEFORE ingredient matching. A certification is stronger evidence than any ingredient match.",
    "terms": [
      "Non-GMO Project Verified",
      "USDA Organic",
      "Certified Organic",
      "EU Organic"
    ],
    "on_match": {
      "likelihood": "Low",
      "confidence": "High",
      "stop_further_scoring": true
    }
  },
  "explicit_crop_matches": {
    "note": "Ingredient directly names a high-GMO-adoption crop. These count toward the likelihood score.",
    "entries": [
      {
        "crop_family": "corn",
        "aliases": [
          "corn",
          "corn starch",
          "cornstarch",
          "corn syrup",
          "high fructose corn syrup",
          "corn oil",
          "dextrose (corn-derived)"
        ]
      },
      {
        "crop_family": "soy",
        "aliases": [
          "soy",
          "soybean",
          "soybean oil",
          "soy lecithin",
          "soy protein",
          "textured vegetable protein"
        ]
      },
      {
        "crop_family": "canola",
        "aliases": [
          "canola",
          "canola oil",
          "rapeseed oil"
        ]
      },
      {
        "crop_family": "cotton",
        "aliases": [
          "cotton",
          "cottonseed",
          "cottonseed oil"
        ]
      },
      {
        "crop_family": "sugar_beet",
        "aliases": [
          "sugar beet",
          "beet sugar"
        ]
      },
      {
        "crop_family": "alfalfa",
        "aliases": [
          "alfalfa"
        ]
      },
      {
        "crop_family": "papaya",
        "aliases": [
          "papaya"
        ]
      },
      {
        "crop_family": "apple",
        "aliases": [
          "apple"
        ]
      },
      {
        "crop_family": "zucchini",
        "aliases": [
          "zucchini",
          "summer squash"
        ]
      },
      {
        "crop_family": "potato",
        "aliases": [
          "potato"
        ]
      }
    ]
  },
  "ambiguous_derivative_matches": {
    "note": "Ingredients that MAY derive from a GMO crop but the label does not disclose the source. Presence lowers confidence, not likelihood. The 'any unspecified vegetable [X]' catch-all is enforced in engine code (gmoEngine.classifyToken), not as fixed phrases here.",
    "entries": [
      {
        "ingredient": "citric acid",
        "possible_sources": [
          "corn",
          "beet",
          "synthetic"
        ]
      },
      {
        "ingredient": "food acid",
        "possible_sources": [
          "corn",
          "beet",
          "synthetic"
        ]
      },
      {
        "ingredient": "ascorbic acid",
        "possible_sources": [
          "corn",
          "synthetic"
        ]
      },
      {
        "ingredient": "maltodextrin",
        "possible_sources": [
          "corn",
          "rice",
          "potato"
        ]
      },
      {
        "ingredient": "vegetable oil (unspecified)",
        "possible_sources": [
          "soy",
          "canola",
          "corn",
          "palm"
        ]
      },
      {
        "ingredient": "natural flavors",
        "possible_sources": [
          "unknown"
        ]
      },
      {
        "ingredient": "xanthan gum",
        "possible_sources": [
          "corn",
          "soy",
          "wheat"
        ]
      },
      {
        "ingredient": "sugar (unspecified)",
        "possible_sources": [
          "sugar beet",
          "sugarcane"
        ]
      },
      {
        "ingredient": "molasses",
        "possible_sources": [
          "sugar beet",
          "sugarcane"
        ]
      },
      {
        "ingredient": "cellulose",
        "possible_sources": [
          "various plant sources"
        ]
      },
      {
        "ingredient": "soy hemoglobin",
        "possible_sources": [
          "soy"
        ]
      }
    ]
  },
  "low_risk_tokens": [
    "salt",
    "water",
    "vinegar",
    "pepper",
    "garlic",
    "onion",
    "spices",
    "sugar",
    "molasses",
    "honey",
    "oil",
    "vegetable oil",
    "flour",
    "rice",
    "wheat",
    "natural flavors",
    "natural flavoring",
    "monk fruit",
    "stevia",
    "xanthan gum",
    "citric acid",
    "fruit juice",
    "puree",
    "vinegar"
  ],
  "likelihood_scoring": {
    "method": "Count N = number of distinct crop_family values matched from explicit_crop_matches only. Ambiguous derivatives never count toward N.",
    "tiers": [
      {
        "N": 0,
        "likelihood": "Low"
      },
      {
        "N": 1,
        "likelihood": "Medium"
      },
      {
        "N": "2+",
        "likelihood": "High"
      }
    ]
  },
  "confidence_scoring": {
    "method": "Points system. Factors below award points; ambiguous-derivative penalty applies once per product when ambiguous matches exist with no explicit crop.",
    "factors": [
      {
        "factor": "Ingredient list completeness",
        "condition": "Full list OCR'd, no visible truncation",
        "points": 2
      },
      {
        "factor": "Product identification",
        "condition": "Barcode matched an Open Food Facts entry",
        "points": 2
      },
      {
        "factor": "Lookup match rate",
        "condition": ">=80% of extracted ingredients recognized",
        "points": 1
      },
      {
        "factor": "Certification clarity",
        "condition": "Cert statement clearly readable either way",
        "points": 1
      },
      {
        "factor": "Ambiguous-derivative penalty",
        "condition": "One or more ambiguous derivatives matched with NO explicit crop found elsewhere",
        "points": -1
      }
    ],
    "tiers": [
      {
        "points": "4-5",
        "confidence": "High"
      },
      {
        "points": "2-3",
        "confidence": "Medium"
      },
      {
        "points": "0-1 or negative",
        "confidence": "Low"
      }
    ]
  }
}
$shfconfig$::jsonb,
  false,
  null
)
on conflict (category, version) do update
  set config_json  = excluded.config_json,
      is_published = excluded.is_published,
      published_at = excluded.published_at;

-- 2. Retire the superseded ruleset.
update public.lookup_config
   set is_published = false,
       published_at = null
 where category = 'gmo_food'
   and is_published
   and version <> '1.1';

-- 3. Promote the new one. It is unpublished from the upsert above, so flip it
--    now that nothing else holds the partial-unique slot.
update public.lookup_config
   set is_published = true,
       published_at = now()
 where category = 'gmo_food'
   and version = '1.1';

commit;

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------
select
  version,
  is_published,
  published_at,
  config_json ->> 'version' as json_version,
  -- The client refuses to load a row where these two disagree.
  (config_json ->> 'version' = version) as version_agrees,
  jsonb_array_length(config_json -> 'explicit_crop_matches' -> 'entries') as crop_families
from public.lookup_config
where category = 'gmo_food'
order by is_published desc, version;
