// Generates supabase/publish-gmo-v1.1.sql from data/gmo_lookup_config_v1.0.json.
//
// Why generate instead of hand-writing: the published config_json MUST match
// data/gmo_lookup_config_v1.0.json, because the client rejects any row whose
// config_json.version disagrees with the version column
// (src/lib/config/lookupConfig.ts: `config.version === data.version`). A
// hand-edited copy is exactly how those two drift apart.
//
// Why SQL and not the REST API: `one_published_per_category` is a partial unique
// index allowing only ONE published row per category. Unpublishing v1.0 and
// publishing v1.1 are two statements that MUST share a transaction, otherwise
// there is a window holding no published ruleset and every scan landing in it
// fails closed with "No valid published ruleset is available". PostgREST cannot
// do that; a single SQL script can.
//
// Run: npm run publish:gmo   (only writes the SQL; it never touches the database)

import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = new URL("../data/gmo_lookup_config_v1.0.json", import.meta.url);
const TARGET = new URL("../supabase/publish-gmo-v1.1.sql", import.meta.url);

const config = JSON.parse(readFileSync(SOURCE, "utf8"));

if (!config.version) throw new Error("Source config has no version field.");
if (config.version === "1.0") {
  throw new Error(
    "Source config still says version 1.0 - the v1.1 corrections have not been applied."
  );
}

// Dollar-quote the JSON so no escaping question can corrupt it. The tag is
// unique enough that it cannot collide with the payload.
const TAG = "$shfconfig$";
if (JSON.stringify(config).includes(TAG)) {
  throw new Error("Payload contains the dollar-quote tag; pick another.");
}

const version = config.version;
const families = config.explicit_crop_matches.entries.length;

const header = `-- Publish the GMO lookup config v${version}.
--
-- Generated by scripts/build-publish-gmo-v1.1.mjs - do not hand-edit. Re-run
-- that script after any change to data/gmo_lookup_config_v1.0.json.
--
-- WHY THIS MUST BE ONE TRANSACTION
--   create unique index one_published_per_category
--     on lookup_config (category) where is_published;
-- permits exactly ONE published ruleset per category. Unpublishing v1.0 and
-- publishing v${version} are therefore two statements that must not be
-- separable: between them the table would hold no published config, and every
-- scan landing in that window fails closed with
-- "No valid published ruleset is available". PostgREST cannot do that; a single
-- SQL script can.
--
-- HOW TO RUN
--   1. Supabase Dashboard -> your project -> SQL Editor -> New query
--   2. Paste this whole file -> Run
--   3. Read the verification SELECT at the bottom. Expect exactly one row with
--      version = '${version}', is_published = true, version_agrees = true,
--      crop_families = ${families}.
--
-- SAFE TO RE-RUN: the insert is an upsert on (category, version).
--
-- NOTE: clients cache the published config in IndexedDB for 5 minutes
-- (CACHE_MAX_AGE in src/lib/config/lookupConfig.ts), so a device that scanned
-- moments before this ran keeps using v1.0 until that window elapses.
--
-- ROLLBACK: flip the is_published flags back to v1.0 in the same transaction
-- shape - unpublish v${version}, publish v1.0.

begin;`;

const body = `-- 1. Land the new ruleset UNPUBLISHED first, so it is fully present
--    in the table before anything starts serving from it.
insert into public.lookup_config (category, version, config_json, is_published, published_at)
values (
  'gmo_food',
  '${version}',
  ${TAG}
${JSON.stringify(config, null, 2)}
${TAG}::jsonb,
  false,
  null
)
on conflict (category, version) do update
  set config_json  = excluded.config_json,
      is_published = excluded.is_published,
      published_at = excluded.published_at;

-- 2. Retire the superseded ruleset.
update public.lookup_config
   set is_published = false,
       published_at = null
 where category = 'gmo_food'
   and is_published
   and version <> '${version}';

-- 3. Promote the new one. It is unpublished from the upsert above, so flip it
--    now that nothing else holds the partial-unique slot.
update public.lookup_config
   set is_published = true,
       published_at = now()
 where category = 'gmo_food'
   and version = '${version}';

commit;

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------
select
  version,
  is_published,
  published_at,
  config_json ->> 'version' as json_version,
  -- The client refuses to load a row where these two disagree.
  (config_json ->> 'version' = version) as version_agrees,
  jsonb_array_length(config_json -> 'explicit_crop_matches' -> 'entries') as crop_families
from public.lookup_config
where category = 'gmo_food'
order by is_published desc, version;
`;

const sql = [header, body].join("\n\n");

// Everything outside the dollar-quoted payload must be plain ASCII, so the file
// can be pasted into the SQL Editor without re-encoding surprises. Ordinary
// whitespace is fine; this is really a guard against smart quotes and dashes.
const parts = sql.split(TAG);
if (parts.length !== 3) throw new Error("Dollar-quote tag count is wrong.");
const scaffolding = parts[0] + parts[2];
const offenders = [...new Set([...scaffolding])].filter((ch) => {
  if (ch === "\n" || ch === "\r" || ch === "\t") return false;
  const c = ch.codePointAt(0);
  return c < 0x20 || c > 0x7e;
});
if (offenders.length > 0) {
  throw new Error(
    `SQL scaffolding contains non-ASCII characters: ${JSON.stringify(offenders.join(""))}`
  );
}

writeFileSync(TARGET, sql, "utf8");
process.stdout.write(
  `Created supabase/publish-gmo-v1.1.sql for GMO ruleset v${version} (${families} crop families)\n`
);
