-- Backfill oral-care catalogue rows with the engine's per-compound detail
-- (the ppm the engine actually classified on).
--
-- WHY: the curated import in supabase/import-fluoride-products.sql was generated
-- before fluorideEngine published `detail` on an active_compound match. Stored
-- rows therefore had no ppm, so the result gauge showed "No data" for every
-- catalogue match — while a cold scan of the SAME label showed e.g. "1500 ppm".
-- Re-running the import does not help: it skips rows whose name already exists.
--
-- Idempotent: sets matched_terms to the engine-derived values for these rows.

update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Crest 3D White Radiant Mint'));
update public.products set matched_terms = '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"1099 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Colgate Total Clean Mint'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1500 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Sensodyne Pronamel Daily Protection'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Tom''s of Maine Simply White Fluoride-Free'));
update public.products set matched_terms = '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"1000 ppm"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Hello Simply White Whitening Toothpaste'));
update public.products set matched_terms = '[{"term":"nano-hydroxyapatite","normalized":"Nano-hydroxyapatite","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Boka Ela Mint Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1080 ppm"},{"term":"sodium bicarbonate","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Arm & Hammer Advance White Extreme Whitening'));
update public.products set matched_terms = '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"1099 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Parodontax Clean Mint Gum Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Marvis Classic Strong Mint'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Jason Simply Nude Fluoride-Free Toothpaste'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Red Seal Natural Herbal Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"1052 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Close-Up Cinnamon Red Gel Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"1000 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Pepsodent Cavity Protection Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1080 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Aim Cavity Protection Ultra Mint Gel'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"},{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Oral-B Pro-Expert All-in-One'));
update public.products set matched_terms = '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"1447 ppm"},{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Signal Family Care Herbal Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"},{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Blend-a-med Complete Protect 7'));
update public.products set matched_terms = '[{"term":"amine fluoride","normalized":"Amine Fluoride","kind":"active_compound","detail":"1400 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Elmex Anti-Caries Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1450 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Aronal Strengthening Toothpaste'));
update public.products set matched_terms = '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"default ppm for this compound"},{"term":"amine fluoride","normalized":"Amine Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Meridol Gum Protection Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1500 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Dontodent Complete 5'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1450 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Dentalux Junior 6+'));
update public.products set matched_terms = '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Vitis Anticaries Toothpaste'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('KORRES Anise & Eucalyptus Fluoride-Free'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Dr. Hauschka Med Fortifying Mint Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium bicarbonate","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Weleda Salt Toothpaste'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Lavera Complete Care Fluoride-Free'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Desert Essence Tea Tree Oil Toothpaste'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"sodium bicarbonate","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Kingfisher Baking Soda Fluoride-Free'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Colgate Max Fresh Nightfall Mint'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1080 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Colgate Kids 2-in-1 Watermelon'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Crest Kid''s Strawberry Rush'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1080 ppm"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('TheraBreath Fresh Breath Toothpaste'));
update public.products set matched_terms = '[{"term":"hydroxyapatite","normalized":"Nano-hydroxyapatite","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Risewell Mineral Toothpaste'));
update public.products set matched_terms = '[{"term":"nano-hydroxyapatite","normalized":"Nano-hydroxyapatite","kind":"active_compound","detail":"default ppm for this compound"},{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Bite Toothpaste Bits Mint'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Native Whitening Toothpaste Flouride-Free'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Burt''s Bees Purely White Fluoride Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1094 ppm"},{"term":"xylitol","normalized":"Xylitol","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Moon Stain Removal Fluoride Toothpaste'));
update public.products set matched_terms = '[{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Davids Natural Toothpaste Peppermint'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"},{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Ciptadent Maxi Fresh'));
update public.products set matched_terms = '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"},{"term":"calcium carbonate","normalized":"Calcium Carbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Pepsodent Action 123'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1000 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Darlie Double Action Mint'));
update public.products set matched_terms = '[{"term":"sodium monofluorophosphate","normalized":"Sodium Monofluorophosphate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Zact Lion Smoker''s Toothpaste'));
update public.products set matched_terms = '[{"term":"hydroxyapatite","normalized":"Nano-hydroxyapatite","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Sangi Apagard Premio'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"1450 ppm"},{"term":"baking soda","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Lion Clinica Advantage Toothpaste'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Sunstar Ora2 Me Stain Clear'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('GUM Dental Paste Toothpaste'));
update public.products set matched_terms = '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"1099 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Sensodyne Repair & Protect'));
update public.products set matched_terms = '[{"term":"stannous fluoride","normalized":"Stannous Fluoride","kind":"active_compound","detail":"1099 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Sensodyne Rapid Relief'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"500 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('ACT Restoring Anticavity Fluoride Mouthwash'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"225 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Colgate Phos-Flur Anticavity Rinse'));
update public.products set matched_terms = '[{"term":"sodium fluoride","normalized":"Sodium Fluoride","kind":"active_compound","detail":"200 ppm"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Listerine Total Care Anticavity Mouthwash'));
update public.products set matched_terms = '[]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('Listerine Zero Alcohol Antiseptic Mouthwash'));
update public.products set matched_terms = '[{"term":"sodium bicarbonate","normalized":"Sodium Bicarbonate","kind":"active_compound","detail":"default ppm for this compound"}]'::jsonb where category = 'oral_care' and lower(btrim(name)) = lower(btrim('TheraBreath Fresh Breath Oral Rinse (Green)'));
